version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini # Opcional: Para configurações personalizadas de PHP
    env_file:
      - .env # Carrega o arquivo .env do Laravel
    networks:
      - laravel

    depends_on:
      - db
    ports:
      - "8000:8000" # Porta para acessar o Laravel

    command: >
      sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  vite:
    image: node:18
    container_name: vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173" # Porta do Vite para desenvolvimento

  db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - "5432:5432"

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
    driver: local
